baseURL: https://mychrispportfolio.netlify.app/
languageCode: en-us
title: Christoph's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Dive in
    subtitle: |-
      If you are seeking a place to loose yourself for hours on end, look no further! On this website, you can learn more about myself and my work.
    title: "Hello there, I am Christoph! Welcome to my Domain!"
  blog: {}
  contact:
    address:
      - city: London, W1U 5ER
        country: United Kingom
        street: 7 Tenby Mansions, Nottingham Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email: 
      - email: cplachutta.mam2023@london.edu
        title: Email
    enable: yes
    formEmail: f/xnqrplkd
    phone:
      - phone: +44 74 964 977 72
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Intellectual Property of Christoph Plachutta
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/christophthehereo/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/christoph_plachutta/
      - icon: fa-github
        label: GitHub
        url: https://github.com/ChrisPlta
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/christophplachutta/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Download my CV
        url: CV/ChristophPlachutta_CV.pdf
    button2:
      - name: My Guilty Pleasure
        url: https://youtu.be/mdTCMDCMV7c
    links:
      - name: Home
        url: '#'
      - name: About me
        url: fun_stuff/about_me
      - name: My Work
        url: blogs
#      - name: Fun Stuff
#        url: personal
    menu: Menu
    subtitle: By HTML5 Up
    title: Christoph Plachutta's Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg
        subtitle: A short summary of my life up to this point! Actively living to collect material for future additions.
        title: About me
        url: fun_stuff/about_me
      - image: plachutta.jpg
        subtitle: When you get the chance to visit Vienna, you should treat yourself to the emperor´s favorite dish - Tafelspitz. Just use our new proprietary online reservation tool, which I managed from conception to implementation.
        title: Plachutta - Eat like the emperor in Vienna
        url: https://www.plachutta.at/en/ 
      - image: spotify.jpg
        subtitle: Ever wonder why a song pops up in your feed, seemingly at random? In this post, we discover the information spotify stores on its songs and whether they indicate a song´s popularity.
        title: What makes a song popular on Spotify? 
        url: blogs/spotify
      - image: omega_paygap.jpg
        subtitle: If you have watched any of the latest James Bond movies, you might have noticed 007 sporting a lovely Omega watch. While it is an expensive accessory, surely his female co-agents can afford it just the same. But what about the employees at Omega? Do they receive equal pay?
        title: What is the sigma at Omega?
        url: blogs/omega_paygap
      - image: climate_change.jpg
        subtitle: A topic discussed even more than whether Mark Zuckerberg is indeed a lizard, climate change poses a threat to the entire world. But rathern than listening to millions of different media claims, let us look at the data ourselves!
        title: Climate change - hoax or fact?
        url: blogs/climate_change
      - image: animal_rescue.jpg
        subtitle: Have you ever watched one of those "Animal Fail Compilation" videos on Youtube, where cats miss the ledge after leaping or horses run headfirst into a wired fence?  I always wondered what happened to these animals after the video cut. I therefore took a look at some animal rescue data from the London Fire Brigade.
        title: SOS - My horse is stuck on a tree!
        url: blogs/animal_rescue
  two:
    buttonText: Keep Reading
    enable: yes
    subtitle: "Still haven't had your fill? Don't worry, there is more for you to discover. By clicking the button below, you will have access to the entire range of my work!
    As I am still new to the world of data science, please be patient while I build up my portfolio. I will always have the latest posts on the landing page for you to stay up to date.
    If you have any wishes for future analysis you would like me to look into, please use the form below to submit them. I am looking forward to hearing your ideas!"
    title: MORE CONTENT
    url: blogs
