baseURL: https://mychrispportfolio.netlify.app/
languageCode: en-us
title: Christoph's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Dive in
    subtitle: |-
      If you are seeking a place to loose yourself for hours on end, look no further! On this website, you can learn more about myself, my experience, and some other fun tidbits to explore!
    title: "Hello there, I am Christoph!\nWelcome to my Domain!"
  blog: {}
  contact:
    address:
      - city: London, W1U 5ER
        country: United Kingom
        street: 7 Tenby Mansions, Nottingham Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email: 
      - email: cplachutta.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 74 964 977 72
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Intellectual Property of Christoph Plachutta
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/christophthehereo/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/christoph_plachutta/
      - icon: fa-github
        label: GitHub
        url: https://github.com/ChrisPlta
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/christophplachutta/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Download my CV
        url: CV/ChristophPlachutta_CV.pdf
    button2:
      - name: My Guilty Pleasure
        url: https://youtu.be/mdTCMDCMV7c
    links:
      - name: Home
        url: '#'
      - name: About me
        url: personal/about_me
      - name: My Work
        url: blogs
#      - name: Fun Stuff
#        url: personal
    menu: Menu
    subtitle: By HTML5 Up
    title: Christoph Plachutta's Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg
        subtitle: A short summary of my life up to this point! Actively living to collect material for future additions.
        title: About me
        url: fun_stuff/about_me
      - image: spotify.jpg
        subtitle: Ever wonder why a song pops up in your feed, seemingly at random? In this post, we discover the information spotify stores on its songs and
        whether they indicate a song´s popularity.
        title: What makes a song popular on Spotify? 
        url: blogs/spotify
      - image: climate_change.jpg
        subtitle: A topic discussed even more than whether Mark Zuckerberg is indeed a lizard, climate change poses a threat to the entire world. But apart from 
        listening to millions of different media claims, let us look at the data ourselves!
        title: Climate Change - Hoax or Fact?
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
